// Phase 8C — creates the three demo pots, then (per-user-batch, see
// writeUserBatch below) adds members, records payments, and writes real
// picks/predictions for both the already-"finished" history gameweeks AND
// the interactive live gameweek (a subset of users only — some people
// haven't picked yet is realistic), and finally settles the history
// gameweeks. All through the exact same validateEntry()/settle() calls
// submit-pick5-picks/submit-lms-pick/submit-predictor-picks/settle-gameweek
// use, so standings, LMS eliminations, jackpot/prize notifications, and
// leaderboards all fall out of the real Game Engine, not hand-written
// demo-only logic. The live gameweek is never settled here — that is
// demo-gameweek-control's job, once its own timeline events bring every
// fixture to 'finished'.
//
// Batched by user, not done in one pass (Slice 1 correction): the local
// Edge Runtime enforces a hard ~2s CPU-time budget per invocation
// (confirmed live — generating 10 users in one call reliably tripped
// "early termination has been triggered" in the container logs). This is
// very likely a real platform constraint, not a local-only quirk, so
// demo-generate-data/index.ts drives this file's functions across multiple
// separate invocations (one per user batch) rather than a single call
// covering every user — see that file's own step dispatcher.

import type { SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { resolveEngine } from '../game-engine/dispatcher.ts'
import '../game-engine/pick5/index.ts'
import '../game-engine/lms/index.ts'
import '../game-engine/predictor/index.ts'
import type { GameEntry } from '../game-engine/types.ts'
import { finalizeHistoryGameweekTiming, type DemoLeagueData, type DemoPlayer } from './generateLeague.ts'
import type { DemoUser } from './generateUsers.ts'
import { makeRng } from './names.ts'

export interface DemoPots {
  pick5PotId: string
  lmsPotId: string
  predictorPotId: string
}

const ctxFor = (sb: SupabaseClient) => ({ supabase: sb, now: () => new Date() })

// Some users simply haven't submitted for the live gameweek yet — a real,
// visible "not everyone has picked" state, not every synthetic user filling
// in every gameweek like a robot would.
const LIVE_GAMEWEEK_SUBMIT_RATE = 0.7

async function createDemoPot(
  sb: SupabaseClient,
  name: string,
  gameType: 'pick5' | 'last_man_standing' | 'score_predictor',
  leagueId: number,
  seasonId: number,
  createdBy: string,
  startGameweekId?: number
): Promise<string> {
  const { data: pot, error } = await sb
    .from('pots')
    .insert({
      name,
      description: 'Generated by the Demo Centre — safe to reset or delete at any time.',
      status: 'active',
      season_id: seasonId,
      league_id: leagueId,
      created_by: createdBy,
      game_type: gameType,
      entry_fee: 5,
      start_gameweek_id: startGameweekId ?? null,
    })
    .select('id')
    .single()
  if (error) throw new Error(`Failed to create demo ${gameType} pot: ${error.message}`)

  const { error: memberError } = await sb
    .from('pot_members')
    .insert({ pot_id: pot.id, user_id: createdBy, role: 'admin' })
  if (memberError) throw new Error(`Failed to add demo pot creator: ${memberError.message}`)

  return pot.id
}

export async function generateDemoPots(
  sb: SupabaseClient,
  league: DemoLeagueData,
  createdBy: string
): Promise<DemoPots> {
  // Real bug caught live (Phase 8C verification sprint): LmsEngine's own
  // calculateScore()/settle() both derive "which pots are mine to process"
  // via getEligibleLmsPotIds(), which filters `start_gameweek_id <=
  // gameweekId` — a NULL start_gameweek_id fails that comparison for every
  // gameweek (Postgres NULL comparisons are never true), so an LMS pot
  // created without one is invisible to its own engine forever, not just
  // for this generation run. Real organiser-created LMS pots always set
  // this at creation; the demo pot must too. Earliest 'history' gameweek —
  // not gameweek 1 of the real calendar, since this is the demo league's
  // own numbering.
  const firstHistoryGw = [...league.gameweeks]
    .filter((g) => g.role === 'history')
    .sort((a, b) => a.number - b.number)[0]

  const pick5PotId = await createDemoPot(sb, 'Demo Pick 5', 'pick5', league.leagueId, league.seasonId, createdBy)
  const lmsPotId = await createDemoPot(sb, 'Demo Last Man Standing', 'last_man_standing', league.leagueId, league.seasonId, createdBy, firstHistoryGw?.id)
  const predictorPotId = await createDemoPot(sb, 'Demo Score Predictor', 'score_predictor', league.leagueId, league.seasonId, createdBy)
  return { pick5PotId, lmsPotId, predictorPotId }
}

function eligiblePick5Players(players: DemoPlayer[], teamId: number): DemoPlayer[] {
  return players.filter((p) => p.teamId === teamId && p.position !== 'Goalkeeper')
}

async function addMembersBatch(sb: SupabaseClient, pots: DemoPots, users: DemoUser[]): Promise<void> {
  const rows = [pots.pick5PotId, pots.lmsPotId, pots.predictorPotId].flatMap((potId) =>
    users.map((u) => ({ pot_id: potId, user_id: u.id, role: 'member' as const }))
  )
  const { error } = await sb.from('pot_members').insert(rows)
  if (error) throw new Error(`Failed to add demo members: ${error.message}`)
}

// Realistic-looking payment mix: most paid, some outstanding. Plain bulk
// insert, deliberately not admin-actions' upsertEntryPayment helper — that
// helper's whole purpose is safely handling a possibly-already-existing
// row (a real admin correcting a real payment), which cannot happen here:
// every row in this batch is for a brand-new synthetic user's brand-new
// entry_payments row. Reusing it would mean one extra lookup query per
// row for no reason, real CPU-time cost this file can't afford to waste.
//
// Real bug caught live (Phase 8C verification sprint): every pot used to
// get scope='season'/gameweek_id=null rows here, but Pick5Engine.settle()
// reads payments scoped 'gameweek' for the exact gameweek being settled
// (docs/business-rules.md — Pick 5 is a weekly entry fee, unlike LMS/
// Predictor's one-time season fee). A season-scoped row never matches that
// lookup, so every demo Pick5 entry read as unpaid and settle() voided all
// of them, every gameweek — the "realistic paid/unpaid mix" requirement
// silently became "always 100% void" for Pick 5 specifically. Fixed by
// writing one gameweek-scoped row per (user, gameweek) for Pick 5, keeping
// LMS/Predictor's real one-time season-scoped model unchanged.
async function recordPaymentsBatch(
  sb: SupabaseClient,
  pots: DemoPots,
  gws: DemoLeagueData['gameweeks'],
  users: DemoUser[],
  markedBy: string,
  seed: number
): Promise<void> {
  const rng = makeRng(seed + 2)
  const now = new Date().toISOString()

  const pick5Rows = gws.flatMap((gw) =>
    users.map((u) => ({
      pot_id: pots.pick5PotId,
      user_id: u.id,
      gameweek_id: gw.id,
      scope: 'gameweek' as const,
      is_paid: rng() < 0.85,
      marked_by: markedBy,
      marked_at: now,
    }))
  )
  const seasonScopedRows = [pots.lmsPotId, pots.predictorPotId].flatMap((potId) =>
    users.map((u) => ({
      pot_id: potId,
      user_id: u.id,
      gameweek_id: null,
      scope: 'season' as const,
      is_paid: rng() < 0.85,
      marked_by: markedBy,
      marked_at: now,
    }))
  )
  const { error } = await sb.from('entry_payments').insert([...pick5Rows, ...seasonScopedRows])
  if (error) throw new Error(`Failed to record demo payments: ${error.message}`)
}

async function writePick5PicksBatch(
  sb: SupabaseClient,
  potId: string,
  league: DemoLeagueData,
  gws: DemoLeagueData['gameweeks'],
  users: DemoUser[],
  seed: number
): Promise<void> {
  const rng = makeRng(seed + 3)
  const ctx = ctxFor(sb)

  for (const gw of gws) {
    const fixtures = league.fixturesByGameweek.get(gw.id) ?? []
    const allPlayersInPlay = fixtures.flatMap((f) => [
      ...eligiblePick5Players(league.players, f.homeTeamId),
      ...eligiblePick5Players(league.players, f.awayTeamId),
    ])

    for (const user of users) {
      if (gw.role === 'live' && rng() >= LIVE_GAMEWEEK_SUBMIT_RATE) continue

      const { data: entry, error: entryError } = await sb
        .from('game_entries')
        .insert({ pot_id: potId, user_id: user.id, gameweek_id: gw.id, entry_scope: 'gameweek' })
        .select()
        .single()
      if (entryError) throw new Error(`Failed to create Pick5 demo entry: ${entryError.message}`)

      const { error: extError } = await sb.from('game_entry_pick5').insert({ game_entry_id: entry.id })
      if (extError) throw new Error(`Failed to create Pick5 demo entry extension: ${extError.message}`)

      const shuffled = [...allPlayersInPlay].sort(() => rng() - 0.5)
      const picks = shuffled.slice(0, 5).map((p) => ({ playerId: p.id }))

      const gameEntry: GameEntry = {
        id: entry.id,
        potId,
        userId: user.id,
        gameweekId: gw.id,
        entryScope: 'gameweek',
        status: 'pending',
        payoutAmount: 0,
        settledAt: null,
      }
      await resolveEngine('pick5').validateEntry(ctx, gameEntry, picks)

      const rows = picks.map((pick, index) => ({
        game_entry_id: entry.id,
        pick_position: index + 1,
        player_id: pick.playerId,
      }))
      const { error: picksError } = await sb.from('pick5_picks').insert(rows)
      if (picksError) throw new Error(`Failed to write Pick5 demo picks: ${picksError.message}`)
    }
  }
}

async function writeLmsPicksBatch(
  sb: SupabaseClient,
  potId: string,
  league: DemoLeagueData,
  gws: DemoLeagueData['gameweeks'],
  users: DemoUser[],
  seed: number
): Promise<void> {
  const ctx = ctxFor(sb)
  const rng = makeRng(seed + 6)

  for (const user of users) {
    const { data: entry, error: entryError } = await sb
      .from('game_entries')
      .insert({ pot_id: potId, user_id: user.id, entry_scope: 'season' })
      .select()
      .single()
    if (entryError) throw new Error(`Failed to create LMS demo entry: ${entryError.message}`)

    const { error: extError } = await sb.from('game_entry_lms').insert({ game_entry_id: entry.id })
    if (extError) throw new Error(`Failed to create LMS demo entry extension: ${extError.message}`)

    const usedTeamIds = new Set<number>()
    for (const gw of gws) {
      if (gw.role === 'live' && rng() >= LIVE_GAMEWEEK_SUBMIT_RATE) continue

      // Real bug caught live (Phase 9 — Demo Gameweek verification): this
      // used to be `teamsInPlay.find((t) => !usedTeamIds.has(t))` — the
      // FIRST unused team in a fixed, identical order every user shares
      // (the same `league.fixturesByGameweek` object) — so every synthetic
      // LMS user picked the exact same team every gameweek (confirmed
      // live: 10/10 users on team A in GW1, then the same 10 on team B in
      // GW2), directly the "every user choosing the same team" failure
      // this generator is supposed to avoid. Picking uniformly at random
      // among the still-unused candidates (same seeded `rng`, so still
      // fully reproducible for a given seed) is the fix.
      const fixtures = league.fixturesByGameweek.get(gw.id) ?? []
      const teamsInPlay = fixtures.flatMap((f) => [f.homeTeamId, f.awayTeamId])
      const availableTeams = teamsInPlay.filter((t) => !usedTeamIds.has(t))
      if (availableTeams.length === 0) continue // ran out of unused teams for this synthetic user — skip, not fatal
      const choice = availableTeams[Math.floor(rng() * availableTeams.length)]
      usedTeamIds.add(choice)

      const gameEntry: GameEntry = {
        id: entry.id,
        potId,
        userId: user.id,
        gameweekId: null,
        entryScope: 'season',
        status: 'pending',
        payoutAmount: 0,
        settledAt: null,
      }
      await resolveEngine('last_man_standing').validateEntry(ctx, gameEntry, { gameweekId: gw.id, teamId: choice })

      const { error: pickError } = await sb
        .from('lms_team_picks')
        .insert({ game_entry_id: entry.id, gameweek_id: gw.id, team_id: choice })
      if (pickError) throw new Error(`Failed to write LMS demo pick: ${pickError.message}`)
    }
  }
}

async function writePredictorPicksBatch(
  sb: SupabaseClient,
  potId: string,
  league: DemoLeagueData,
  gws: DemoLeagueData['gameweeks'],
  users: DemoUser[],
  seed: number
): Promise<void> {
  const rng = makeRng(seed + 4)
  const ctx = ctxFor(sb)

  for (const user of users) {
    const { data: entry, error: entryError } = await sb
      .from('game_entries')
      .insert({ pot_id: potId, user_id: user.id, entry_scope: 'season' })
      .select()
      .single()
    if (entryError) throw new Error(`Failed to create Predictor demo entry: ${entryError.message}`)

    const { error: extError } = await sb.from('game_entry_predictor').insert({ game_entry_id: entry.id })
    if (extError) throw new Error(`Failed to create Predictor demo entry extension: ${extError.message}`)

    for (const gw of gws) {
      if (gw.role === 'live' && rng() >= LIVE_GAMEWEEK_SUBMIT_RATE) continue

      const fixtures = league.fixturesByGameweek.get(gw.id) ?? []
      if (fixtures.length === 0) continue
      const fixture = fixtures[Math.floor(rng() * fixtures.length)]

      const guessRight = gw.role === 'history' && rng() < 0.3
      const predictedHomeScore = guessRight ? fixture.homeGoals : Math.floor(rng() * 4)
      const predictedAwayScore = guessRight ? fixture.awayGoals : Math.floor(rng() * 4)

      const homePlayers = league.players.filter((p) => p.teamId === fixture.homeTeamId && p.position !== 'Goalkeeper')
      const goalscorerPlayerId = rng() < 0.6 && homePlayers.length > 0
        ? homePlayers[Math.floor(rng() * homePlayers.length)].id
        : null

      const gameEntry: GameEntry = {
        id: entry.id,
        potId,
        userId: user.id,
        gameweekId: null,
        entryScope: 'season',
        status: 'pending',
        payoutAmount: 0,
        settledAt: null,
      }
      await resolveEngine('score_predictor').validateEntry(ctx, gameEntry, {
        gameweekId: gw.id,
        fixtureId: fixture.id,
        predictedHomeScore,
        predictedAwayScore,
        goalscorerPlayerId,
      })

      const { error: pickError } = await sb.from('predictor_fixture_picks').insert({
        game_entry_id: entry.id,
        gameweek_id: gw.id,
        fixture_id: fixture.id,
        predicted_home_score: predictedHomeScore,
        predicted_away_score: predictedAwayScore,
        goalscorer_player_id: goalscorerPlayerId,
      })
      if (pickError) throw new Error(`Failed to write Predictor demo pick: ${pickError.message}`)
    }
  }
}

// One user batch's worth of work: pot membership, payments, and picks
// across all three modes for both history gameweeks and (for a submitting
// subset) the live gameweek. Called once per batch by
// demo-generate-data/index.ts's 'users' step — each call is its own Edge
// Function invocation, its own fresh CPU budget.
export async function writeUserBatch(
  sb: SupabaseClient,
  pots: DemoPots,
  league: DemoLeagueData,
  users: DemoUser[],
  markedBy: string,
  seed: number
): Promise<void> {
  const historyAndLiveGws = league.gameweeks.filter((g) => g.role === 'history' || g.role === 'live')

  await addMembersBatch(sb, pots, users)
  await recordPaymentsBatch(sb, pots, historyAndLiveGws, users, markedBy, seed)
  await writePick5PicksBatch(sb, pots.pick5PotId, league, historyAndLiveGws, users, seed)
  await writeLmsPicksBatch(sb, pots.lmsPotId, league, historyAndLiveGws, users, seed)
  await writePredictorPicksBatch(sb, pots.predictorPotId, league, historyAndLiveGws, users, seed)
}

// Inserts fixture_events for the already-"finished" history fixtures so
// Pick5's player_fixture_goals materialized view (built from fixture_events,
// not fixtures.home_goals/away_goals) has real scorer data matching each
// fixture's final score exactly — otherwise every Pick5 demo pick would
// read zero goals regardless of the scoreline. Never called for the live
// gameweek — its fixture_events are written incrementally by
// demo-gameweek-control as the operator triggers each timeline event. No
// user dependency — called once, during league generation, not per batch.
export async function writeHistoryFixtureEvents(sb: SupabaseClient, league: DemoLeagueData, seed: number): Promise<void> {
  const rng = makeRng(seed + 5)
  const historyGws = league.gameweeks.filter((g) => g.role === 'history')

  for (const gw of historyGws) {
    const fixtures = league.fixturesByGameweek.get(gw.id) ?? []
    for (const fixture of fixtures) {
      const events: {
        fixture_id: number
        player_id: number
        team_id: number
        event_type: string
        minute: number
        is_own_goal: boolean
        is_penalty: boolean
      }[] = []

      const homeScorers = league.players.filter((p) => p.teamId === fixture.homeTeamId && p.position !== 'Goalkeeper')
      const awayScorers = league.players.filter((p) => p.teamId === fixture.awayTeamId && p.position !== 'Goalkeeper')

      for (let i = 0; i < fixture.homeGoals; i++) {
        if (homeScorers.length === 0) break
        const scorer = homeScorers[Math.floor(rng() * homeScorers.length)]
        events.push({
          fixture_id: fixture.id,
          player_id: scorer.id,
          team_id: fixture.homeTeamId,
          event_type: 'goal',
          minute: 1 + Math.floor(rng() * 89),
          is_own_goal: false,
          is_penalty: false,
        })
      }
      for (let i = 0; i < fixture.awayGoals; i++) {
        if (awayScorers.length === 0) break
        const scorer = awayScorers[Math.floor(rng() * awayScorers.length)]
        events.push({
          fixture_id: fixture.id,
          player_id: scorer.id,
          team_id: fixture.awayTeamId,
          event_type: 'goal',
          minute: 1 + Math.floor(rng() * 89),
          is_own_goal: false,
          is_penalty: false,
        })
      }

      if (events.length > 0) {
        const { error } = await sb.from('fixture_events').insert(events)
        if (error) throw new Error(`Failed to write demo history fixture_events: ${error.message}`)
      }
    }
  }
}

// Settles the two history gameweeks through the real dispatcher — refresh
// the materialized view exactly like compute-scores does, calculateScore()
// for all three modes, then settle() (which self-orchestrates
// generateStandings/determineWinner/awardPrize/notifyUsers internally, per
// the Game Engine contract — confirmed by reading pick5/engine.ts's own
// settle() before writing this). Called once, as its own step, after every
// user batch has finished.
export async function settleHistoryGameweeks(sb: SupabaseClient, league: DemoLeagueData): Promise<void> {
  const ctx = ctxFor(sb)
  const ALL_GAME_TYPES = ['pick5', 'last_man_standing', 'score_predictor'] as const
  const historyGws = league.gameweeks.filter((g) => g.role === 'history')

  await finalizeHistoryGameweekTiming(sb, league)

  const { error: refreshError } = await sb.rpc('refresh_player_fixture_goals')
  if (refreshError) throw new Error(`Failed to refresh player_fixture_goals: ${refreshError.message}`)

  for (const gw of historyGws) {
    // Real bug caught live (Phase 8C verification sprint): the real pipeline
    // always locks entries (compute-deadlines) before scoring/settling them
    // (compute-scores/settle-gameweek). This function skipped straight to
    // calculateScore()/settle() — Pick5Engine gates BOTH of those on
    // game_entries.status = 'locked' (its own comment: "Only touches
    // game_entries that are already 'locked'"), so every demo Pick5 entry
    // sat at 'pending' forever, scored zero, and settle() no-op'd via its
    // own `if (!entries?.length) return`. lockEntries() itself is
    // deadline-agnostic (compute-deadlines/index.ts is what checks the
    // deadline before calling it, not lockEntries() itself), so it's safe
    // to call here even though these gameweeks' deadline_utc is
    // deliberately still in the near future (see generateLeague.ts).
    for (const gameType of ALL_GAME_TYPES) {
      await resolveEngine(gameType).lockEntries(ctx, gw.id)
    }
    for (const gameType of ALL_GAME_TYPES) {
      await resolveEngine(gameType).calculateScore(ctx, gw.id)
    }
    for (const gameType of ALL_GAME_TYPES) {
      await resolveEngine(gameType).settle(ctx, gw.id)
    }
    const { error: gwError } = await sb
      .from('gameweeks')
      .update({ status: 'completed' })
      .eq('id', gw.id)
    if (gwError) throw new Error(`Failed to mark demo gameweek ${gw.id} completed: ${gwError.message}`)
  }
}
