// Phase 10B — Part 15. `seasons.name` is free-text and already
// inconsistent live ("2025/26" for the current season vs a bare "2026"
// for another real season row, one of which even has year_end===
// year_start) — never trustworthy for display. Derives the standard
// football-season "2026/27" format from `year_start` alone, which is
// reliable regardless of what the free-text name column holds. Falls back
// to the stored name (then a plain dash) only when year_start itself is
// missing, so a malformed row never renders blank.
export function formatSeasonName(season) {
  if (!season) return '—'
  if (typeof season.year_start === 'number') {
    return `${season.year_start}/${String(season.year_start + 1).slice(-2)}`
  }
  return season.name || '—'
}

// Phase 12, Part 3 — "Hull City vs Man United"-style truncation turned out
// to be two separate problems: not enough card width (fixed in
// Dashboard.jsx's grid) AND every fixture card rendering `short_name`
// ("Man United") instead of the real, full `name` football-data.org
// already synced ("Manchester United FC"). This prefers the full name,
// stripping only a redundant trailing " FC" (a genuine, common naming
// convention — "Arsenal FC" -> "Arsenal", "Manchester United FC" ->
// "Manchester United") without touching names that don't have one
// ("AFC Bournemouth" keeps its real leading "AFC"). Never fabricates a
// name: falls back to short_name, then a plain placeholder, exactly like
// every existing team-name read in this codebase already does.
export function formatTeamName(team) {
  const full = team?.name?.trim()
  if (full) return full.replace(/\s+FC$/i, '')
  return team?.short_name || 'TBD'
}

export function ordinal(n) {
  const s = ['th','st','nd','rd']
  const v = n % 100
  return n + (s[(v - 20) % 10] || s[v] || s[0])
}

export function pluralise(n, word) {
  return `${n} ${word}${n !== 1 ? 's' : ''}`
}

export function truncate(str, max = 24) {
  if (!str) return ''
  return str.length > max ? str.slice(0, max) + '…' : str
}

export function initials(name = '') {
  return name
    .split(' ')
    .slice(0, 2)
    .map((w) => w[0]?.toUpperCase() ?? '')
    .join('')
}

// Phase 25 — extracted from Dashboard.jsx's own greeting logic (found
// live against real data: `handle_new_user()`'s signup default leaves
// `display_name` equal to the account's email until someone explicitly
// changes it — 5 of 57 real profiles at the time this was found, still
// possible for any account created before a display name was set). Any
// place that shows a user's identity (top nav, pot headers, leaderboards,
// member lists) should resolve through this one function rather than
// reading `profile.display_name` directly, so an email never surfaces as
// a person's name anywhere in the app, not just on the Dashboard.
//
// `username` is never itself an email (schema: alphanumeric + underscore
// only) but CAN be the auto-generated `'user_' || substr(id,1,8)` shape
// `handle_new_user()` falls back to when no real username was chosen
// either — that's not a name a human would recognise, so it's treated the
// same as "no usable value" rather than shown as if it were a real name.
const AUTO_USERNAME_RE = /^user_[0-9a-f]{8}$/i
function looksLikeEmail(value) {
  return !!value && value.includes('@') && !value.includes(' ')
}
function looksAutoGenerated(username) {
  return !!username && AUTO_USERNAME_RE.test(username)
}

// Returns the best available human-readable identity for a profile, or
// `null` if nothing usable exists (never fabricates a name) — callers
// decide their own fallback text ("User", "Unknown", etc.) for that case.
export function resolveDisplayName(profile) {
  const displayName = profile?.display_name?.trim() || ''
  const username = profile?.username?.trim() || ''
  if (looksLikeEmail(displayName)) {
    return looksAutoGenerated(username) ? null : (username || null)
  }
  return displayName || (looksAutoGenerated(username) ? null : (username || null))
}

// Convenience for greeting-style contexts ("Welcome back, Ben") that only
// want the first word of whatever resolveDisplayName() returns.
export function resolveFirstName(profile) {
  const name = resolveDisplayName(profile)
  return name?.split(/\s+/)[0] || null
}